### ISSUE TITLE
All errors appear one line above where they should

### ISSUE THREAD

**Issue by ReagentX** [CasperCL/Python-Lint.novaextension#8]
Pylint:

<img width="909" alt="image" src="https://user-images.githubusercontent.com/1920666/94162130-6301ed00-fe54-11ea-8d28-165112b79ea4.png">

Mypy:

<img width="399" alt="image" src="https://user-images.githubusercontent.com/1920666/94162221-7ca33480-fe54-11ea-9395-e0089dec3882.png">

**Comment by CasperCL** [comment]
Hi @ReagentX, thanks for taking time to report this. The issue has reported in #4 and it's been fixed in version 0.2, which I just put live!

**Comment by CasperCL** [comment]
Of course you're welcome to re-open the issue if the problem persists.

**Comment by ReagentX** [comment]
Hi, the issue was not fixed. Please re-open the ticket.

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/1920666/94166107-ed4c5000-fe58-11ea-88bb-ca3889c8bf5b.png">

**Comment by CasperCL** [comment]
Btw, please don't expect a fix within hours as I just finished my (unrelated) work for today. It was a long day so I'm pretty exhausted right now. However you're more than welcome to look into the issue yourself as well.

**Comment by CasperCL** [comment]
@ReagentX Now that I look at your issue again, it seems like a totally unrelated issue to the mypy issue. Like I said, it's been a long day haha, thanks for hanging in there.
Fun story: it's actually Nova's `IssueParser` that subtracts 1 from the line number that it captures using regex. I manually [add one line back](https://github.com/CasperCL/Python-Lint.novaextension/blob/master/Scripts/main.js#L42) after parsing. I'll report this to Panic as well.

Thanks again for reporting this and participating in this open source project and trying to make Nova more accessible for Python users. If you have any ideas you'd want to see added please don't hesitate to create an issue and perhaps take one up!
